#!/bin/sh

if command -v bunx >/dev/null 2>&1; then
  alias runner=bunx
elif command -v npx >/dev/null 2>&1; then
  alias runner=npx
else
  echo "Error: you need either $(bunx) or $(npx) in your PATH to build this!" >&2
  exit 1
fi

./create-deck

runner @marp-team/marp-cli@latest index.md --html
